### ISSUE TITLE
Unable to start starbound when path set correctly but no folder is open

### ISSUE THREAD

**Issue by LyraelRayne** [C0bra5/starbound-build#1]
![image](https://user-images.githubusercontent.com/11632412/29237263-192c9cb6-7f5e-11e7-8716-652b0c3bc786.png)

My guess is because the CWD is undefined, but not sure.

**Comment by LyraelRayne** [comment]
Found the cause. You MUST have a folder open in atom for the CWD to be set, and without a CWD it can't run.

Might be worth adding this to the instructions for getting started!

**Comment by C0bra5** [comment]
that is an idea, it's for the linter integrations to work, I think I can detect the CWD being undefined and post a message that you must have a folder open.
